// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.3
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GeneratedSchemaTypes
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.3")]
	public partial class PersonName : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"PersonName\",\"namespace\":\"GeneratedSchemaTypes\",\"fields\":" +
				"[{\"name\":\"Given\",\"type\":\"string\"},{\"name\":\"Family\",\"type\":\"string\"}]}");
		private string _Given;
		private string _Family;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return PersonName._SCHEMA;
			}
		}
		public string Given
		{
			get
			{
				return this._Given;
			}
			set
			{
				this._Given = value;
			}
		}
		public string Family
		{
			get
			{
				return this._Family;
			}
			set
			{
				this._Family = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Given;
			case 1: return this.Family;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Given = (System.String)fieldValue; break;
			case 1: this.Family = (System.String)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
