// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: WaffleV2.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Namespace.Waffle.V2 {

  /// <summary>Holder for reflection information generated from WaffleV2.proto</summary>
  public static partial class WaffleV2Reflection {

    #region Descriptor
    /// <summary>File descriptor for WaffleV2.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static WaffleV2Reflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5XYWZmbGVWMi5wcm90byJ4CgZXYWZmbGUSCgoCSWQYASABKAkSEwoES2lu",
            "ZBgCIAEoDjIFLktpbmQSLQoRU2V2aW5nVGVtcGVyYXR1cmUYBCABKA4yEi5T",
            "ZXZpbmdUZW1wZXJhdHVyZRIeCgpDb25kaW1lbnRzGAMgAygOMgouQ29uZGlt",
            "ZW50Kh8KBEtpbmQSCgoGTk9STUFMEAASCwoHQkVMR0lBThABKoQBCglDb25k",
            "aW1lbnQSBwoDSkFNEAASDgoKU09VUl9DUkVBTRABEgoKBkJVVFRFUhACEgkK",
            "BVNVR0FSEAMSEQoNQ0FTSEVXX0JVVFRFUhAEEg8KC01BUExFX1NZUlVQEAUS",
            "EAoMU1RSQVdCRVJSSUVTEAYSEQoNV0hJUFBFRF9DUkVBTRAHKjAKEVNldmlu",
            "Z1RlbXBlcmF0dXJlEgcKA0hPVBAAEggKBENPTEQQARIICgRST09NEAJCFqoC",
            "E05hbWVzcGFjZS5XYWZmbGUuVjJiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Namespace.Waffle.V2.Kind), typeof(global::Namespace.Waffle.V2.Condiment), typeof(global::Namespace.Waffle.V2.SevingTemperature), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Namespace.Waffle.V2.Waffle), global::Namespace.Waffle.V2.Waffle.Parser, new[]{ "Id", "Kind", "SevingTemperature", "Condiments" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum Kind {
    [pbr::OriginalName("NORMAL")] Normal = 0,
    [pbr::OriginalName("BELGIAN")] Belgian = 1,
  }

  public enum Condiment {
    [pbr::OriginalName("JAM")] Jam = 0,
    [pbr::OriginalName("SOUR_CREAM")] SourCream = 1,
    [pbr::OriginalName("BUTTER")] Butter = 2,
    [pbr::OriginalName("SUGAR")] Sugar = 3,
    [pbr::OriginalName("CASHEW_BUTTER")] CashewButter = 4,
    [pbr::OriginalName("MAPLE_SYRUP")] MapleSyrup = 5,
    [pbr::OriginalName("STRAWBERRIES")] Strawberries = 6,
    [pbr::OriginalName("WHIPPED_CREAM")] WhippedCream = 7,
  }

  public enum SevingTemperature {
    [pbr::OriginalName("HOT")] Hot = 0,
    [pbr::OriginalName("COLD")] Cold = 1,
    [pbr::OriginalName("ROOM")] Room = 2,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Waffle : pb::IMessage<Waffle>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Waffle> _parser = new pb::MessageParser<Waffle>(() => new Waffle());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Waffle> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Namespace.Waffle.V2.WaffleV2Reflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Waffle() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Waffle(Waffle other) : this() {
      id_ = other.id_;
      kind_ = other.kind_;
      sevingTemperature_ = other.sevingTemperature_;
      condiments_ = other.condiments_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Waffle Clone() {
      return new Waffle(this);
    }

    /// <summary>Field number for the "Id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Kind" field.</summary>
    public const int KindFieldNumber = 2;
    private global::Namespace.Waffle.V2.Kind kind_ = global::Namespace.Waffle.V2.Kind.Normal;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Namespace.Waffle.V2.Kind Kind {
      get { return kind_; }
      set {
        kind_ = value;
      }
    }

    /// <summary>Field number for the "SevingTemperature" field.</summary>
    public const int SevingTemperatureFieldNumber = 4;
    private global::Namespace.Waffle.V2.SevingTemperature sevingTemperature_ = global::Namespace.Waffle.V2.SevingTemperature.Hot;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Namespace.Waffle.V2.SevingTemperature SevingTemperature {
      get { return sevingTemperature_; }
      set {
        sevingTemperature_ = value;
      }
    }

    /// <summary>Field number for the "Condiments" field.</summary>
    public const int CondimentsFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Namespace.Waffle.V2.Condiment> _repeated_condiments_codec
        = pb::FieldCodec.ForEnum(26, x => (int) x, x => (global::Namespace.Waffle.V2.Condiment) x);
    private readonly pbc::RepeatedField<global::Namespace.Waffle.V2.Condiment> condiments_ = new pbc::RepeatedField<global::Namespace.Waffle.V2.Condiment>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Namespace.Waffle.V2.Condiment> Condiments {
      get { return condiments_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Waffle);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Waffle other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Kind != other.Kind) return false;
      if (SevingTemperature != other.SevingTemperature) return false;
      if(!condiments_.Equals(other.condiments_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (Kind != global::Namespace.Waffle.V2.Kind.Normal) hash ^= Kind.GetHashCode();
      if (SevingTemperature != global::Namespace.Waffle.V2.SevingTemperature.Hot) hash ^= SevingTemperature.GetHashCode();
      hash ^= condiments_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Kind != global::Namespace.Waffle.V2.Kind.Normal) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Kind);
      }
      condiments_.WriteTo(output, _repeated_condiments_codec);
      if (SevingTemperature != global::Namespace.Waffle.V2.SevingTemperature.Hot) {
        output.WriteRawTag(32);
        output.WriteEnum((int) SevingTemperature);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Kind != global::Namespace.Waffle.V2.Kind.Normal) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Kind);
      }
      condiments_.WriteTo(ref output, _repeated_condiments_codec);
      if (SevingTemperature != global::Namespace.Waffle.V2.SevingTemperature.Hot) {
        output.WriteRawTag(32);
        output.WriteEnum((int) SevingTemperature);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (Kind != global::Namespace.Waffle.V2.Kind.Normal) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Kind);
      }
      if (SevingTemperature != global::Namespace.Waffle.V2.SevingTemperature.Hot) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) SevingTemperature);
      }
      size += condiments_.CalculateSize(_repeated_condiments_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Waffle other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.Kind != global::Namespace.Waffle.V2.Kind.Normal) {
        Kind = other.Kind;
      }
      if (other.SevingTemperature != global::Namespace.Waffle.V2.SevingTemperature.Hot) {
        SevingTemperature = other.SevingTemperature;
      }
      condiments_.Add(other.condiments_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 16: {
            Kind = (global::Namespace.Waffle.V2.Kind) input.ReadEnum();
            break;
          }
          case 26:
          case 24: {
            condiments_.AddEntriesFrom(input, _repeated_condiments_codec);
            break;
          }
          case 32: {
            SevingTemperature = (global::Namespace.Waffle.V2.SevingTemperature) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 16: {
            Kind = (global::Namespace.Waffle.V2.Kind) input.ReadEnum();
            break;
          }
          case 26:
          case 24: {
            condiments_.AddEntriesFrom(ref input, _repeated_condiments_codec);
            break;
          }
          case 32: {
            SevingTemperature = (global::Namespace.Waffle.V2.SevingTemperature) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
